/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:df6c5df3-17d1-4af6-ba20-69012a8c1a07",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_eTYDxMxcX",
    "aws_user_pools_web_client_id": "6fomufis4j3kq87spajohnrh3g",
    "oauth": {}
};


export default awsmobile;
